id: PD4111BB1
initial_creation_type: input
source_metadata:
  title: Khenchen Jigme Phuntsok Series
  language: en
  description: 'Works by and about the influential Nyingma teacher and treasure-revealer
    Kyabje Khenchen Jigme Phuntsok Rinpoche (mkhan chen ''jigs med phun tshogs), aka
    Khenpo Jigphun (1933–2004):'
  volume:
    77248cf2717c413180a895f715657b24:
      title: 'The Heart Essence: My Heart''s Advice'
      parent: Advice
    7e3c9c650cf04c3082909bde44fd6663:
      title: Aspiration Prayer
      parent: Aspiration Prayers
    3132acc5fbbd43c1bf54a1530ab768c6:
      title: Aspiration for Future Lives
      parent: Aspiration Prayers
    0f58d3558259408192a32076e17384c7:
      title: Aspiration for the Spread of the Teachings of the Eight Chariots of the
        Practice Lineage
      parent: Aspiration Prayers
    d6b0ccb3711041cfb8f29f420870daae:
      title: Aspiration to be Cared For in Every Lifetime
      parent: Aspiration Prayers
    cfd42456f12346a79421ad1a1471d078:
      title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the
        Enlightened Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton
        Lerab Lingpa'
      parent: Aspiration Prayers
    2e9c4c1d2b054bacbc2b41dab6566826:
      title: 'The Sun of Samantabhadra’s Realm: The Quintessence of Oceanic Prayers
        of Aspiration'
      parent: Aspiration Prayers
    a82aa28c3c5e49ecb54ab6a163f2ea58:
      title: 'The Swift Bestowal of Blessings: A Guru Yoga'
      parent: Guru Yoga
    0c9b3c2ecf4c4671a8135ccb1a6872f9:
      title: Prayer to Khenchen Jigme Phuntsok
      parent: Lineage Prayers
    e6e33bc35d8c4c8096dc0dff127e38a0:
      title: Prayer to the Chain of Rebirths
      parent: Lineage Prayers
    4886c19b521b429cb0ea45470771f389:
      title: 'The Healing Medicine of Faith: A Prayer to the Lineage of the Peaceful
        Sādhana of Mañjuśrī'
      parent: Lineage Prayers
    82eadaf6e76f4a7fa76721ad11814e5d:
      title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind
        Kīla Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Lineage Prayers
    f617960b4b65437c82a4e7fd4a97800a:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    18c3aea08bee405d9aacc053ea7a5824:
      title: Prayer for the Long Life of Khandro Tāre Lhamo
      parent: Long Life Prayers
    e4d97d627eed48d2b5440d9f4b49614d:
      title: Prayer for the Long Life of Pema Norbu, Lord of Siddhas
      parent: Long Life Prayers
    2d45203a354d4d038f0bbc1e090a4c2a:
      title: Upon Arriving at Yangleshö
      parent: Pilgrimage
    13a81ecb620246e1a6b0b89c8d66f9a0:
      title: 'A Lament of Faith: A Short Remembrance of, and Prayer to, My Guru, the
        Wish-Fulfilling Jewel'
      parent: Prayers
    7799c3051d6046b4bd3d97b11178709e:
      title: 'The Sunlight of Blessings: A Prayer'
      parent: Prayers
    63d04f35ac8e45cb85fcf2f9abf39776:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Sādhanas
    99767593842c48f4b0c878e56f5401f6:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Sādhanas
    88707e20b1244c6c9608d11bb5866499:
      title: 'Swift Bestowal of Blessings: A Peaceful Sādhana of Mañjuśrī'
      parent: Sādhanas
    295e73e229314c78b90be9db09e749ce:
      title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the
        Glorious Vajrasattva, a Method of Purification and Accomplishment for Both
        Self and Others'
      parent: Sādhanas
    eecf68567ab94b6c92bc02e110195c36:
      title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
        and Fulfilment'
      parent: Songs
    007146041be64b9aa4975337f687d48e:
      title: 'The Sound of the Divine Drum: Advice at a Time of Victory'
      parent: Songs
    663484783918461b88f5173de834acb2:
      title: 'The Spontaneous Sound of Uncontrived Song: A Lament Recalling the Great
        Guru of Oḍḍiyāna'
      parent: Songs
    71dc55e18fdd4ffa969ff2286df27930:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Vajrakīla
    bb37b54246c44ca4a71ff83bb8be53b6:
      title: Entrusting Activity
      parent: Vajrakīla
    bf1fa9a569cc4bfb89bf54f9991b9bbc:
      title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle'
      parent: Vajrakīla
    6b7ab6ecd43145158dc2af2333190169:
      title: 'Offering Clouds of Samantabhadra: Confession and Fulfilment'
      parent: Vajrakīla
    84a4d48e0317440c932889900abb7aa2:
      title: Offering to the Dharma Guardians of the 'Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle
      parent: Vajrakīla
    6b7ede0b42ae4ebfa826aebb3240cd8b:
      title: The Single Mind Kīla Practice, Part of the 'Neck-Pouch Dagger’ (Purba
        Gulkhukma) Cycle
      parent: Vajrakīla
created_at: '2022-03-01T00:20:10.610283'
last_modified_at: '2022-03-01T00:20:10.610290'
